### ISSUE TITLE
2.10.4 addSubtitle in demo is broken

### ISSUE THREAD

**Issue by rbokel** [bitmovin/bitmovin-player-ui#72]
Hi guys, wenn i click on addSubtitle in the demo (gulp serve), i'm seeing an error in the console 

`bitmovinplayer.js:11 Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined
    at j0z.(anonymous function) [as addSubtitle] (https://bitmovin-a.akamaihd.net/bitmovin-player/stable/7.4/bitmovinplayer.js:11:697015)
    at J1x.(anonymous function).(anonymous function) [as addSubtitle] (https://bitmovin-a.akamaihd.net/bitmovin-player/stable/7.4/bitmovinplayer.js:11:721312)
    at HTMLButtonElement.<anonymous> (http://localhost:9000/:348:33)
    at HTMLButtonElement.dispatch (https://code.jquery.com/jquery-3.1.0.min.js:3:9922)
    at HTMLButtonElement.q.handle (https://code.jquery.com/jquery-3.1.0.min.js:3:7949)
(anonymous function) @ bitmovinplayer.js:11
J1x.(anonymous function).(anonymous function) @ bitmovinplayer.js:11
(anonymous) @ (index):348
dispatch @ jquery-3.1.0.min.js:3
q.handle @ jquery-3.1.0.min.js:3`

**Comment by protyposis** [comment]
Hi Ralf, thanks for reporting. I cannot reproduce this though. Is the player basically working?

**Comment by rbokel** [comment]
yes, the player is working
let me try with a fresh clone

**Comment by rbokel** [comment]
still 
i'm using chrome 62.0.3202.94
and my node is 6.9.1

**Comment by protyposis** [comment]
Ah yeah there are two "addSubtitle" buttons, one under "Playback Control" and one under "Actions". 

The one under "Playback Control" leads to the error because this API function expects a [parameter](https://bitmovin-a.akamaihd.net/bitmovin-player/stable/7/docs/interfaces/playerapi.playerapi-1.html#addsubtitle) that isn't passed in, because the buttons in this section just enumerate the API functions without caring about parameters. All buttons that execute functions without expected parameters will fail there.

The one under "Actions" will work and add a test subtitle to the player.

**Comment by rbokel** [comment]
Yes, that's it. Thanks.
